config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'groups#index'
  mount Sidekiq::Web => '/sidekiq'

  resources :groups, only: [:index, :show] do
    resources :tasks
  end
  get '/groups/:group_id/tasks/:id/test', to: 'tasks#test', as: 'test_group_task'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/light_group.rb
class LightGroup < ApplicationRecord
  has_many :tasks, primary_key: :hue_id

  def self.hue_client
    @hue_client ||= Hue::Client.new
  end

  def self.update_groups
    hue_client.groups.each do |group|
      unless find_by(hue_id: group.id)
        create(name: group.name, hue_id: group.id)
      end
    end
  end

  def lights
    hue_group.lights
  end

  def state(params, duration: 0, brightness: 100)
    return hue_group.set_state(params) unless duration > 0

    if params[:on]
      hue_group.set_state(on: true, brightness: 0)
      hue_group.set_state({ brightness: brightness }, duration)
    end
  end

  private

  def hue_group
    LightGroup.hue_client.group(hue_id)
  end
end

app/models/task.rb
class Task < ApplicationRecord
  has_one :light_group, primary_key: :light_group_id, foreign_key: :hue_id

  DAYS_HASH = {
    1 => 'Monday',
    2 => 'Tuesday',
    4 => 'Wednesday',
    8 => 'Thursday',
    16 => 'Friday',
    32 => 'Saturday',
    64 => 'Sunday'
  }.freeze
  
  def self.pretty_days(bin_days)
    days = []
    DAYS_HASH.each do |key, day|
      days << day if bin_days & key == key
    end

    days.join(', ')
  end

  def pretty_action
    action.sub('_', ' ').capitalize
  end

  def pretty_duration
    duration < 60 ? unit = 'Second' : unit = 'Minute'
    unit == 'Minute' ? time = duration / 60 : time = duration
    string = "#{time} #{unit}"
    string += 's' if time > 1

    return string
  end

end

app/models/task_executor.rb
class TaskExecutor < ApplicationRecord
  ACTION_KEY = {
    'turn_off' => { on: false },
    'turn_on' => { on: true }
  }.freeze

  def self.light_group_class
    LightGroup
  end

  def self.execute(task)
    light_group = light_group_class.find_by(hue_id: task.light_group_id)
    action = ACTION_KEY[task.action]
    puts result = light_group.state(action, duration: task.duration, brightness: task.brightness)
    return :success if result.first['success']

    :fail
  end
end

app/models/task_scheduler.rb
class TaskScheduler < ApplicationRecord

  def self.schedule_tasks
    Task.all.each do |task|
      scehdule_task(task)
    end
  end
  
  def self.scehdule_task(task)
    day = Time.now.strftime("%A")
    return unless Task.pretty_days(task.days).include?(day)

    time = task.time.split(':').map! { |num| num.to_i }
    time = Date.today.midnight + time[0].hours + time[1].minutes
    
    ExecuteTaskJob.set(wait_until: time).perform_later(task.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
    @groups = LightGroup.all
  end

  def show
    @group = LightGroup.find_by(hue_id: params[:id])
  end
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def show
    @group = LightGroup.find_by(hue_id: params[:group_id])
    @task = Task.find(params[:id])
    @days = Task.pretty_days(@task.days)
  end

  def new
    @task = Task.new
    @group = LightGroup.find_by(hue_id: params[:group_id])
  end

  def create
    duration = params['transition-duration'].to_i
    duration *= 60 if params['duration-units'] == 'minutes'

    task = Task.create(
      name: params[:task_name],
      time: params[:time],
      days: binary_days(params),
      action: params[:group_action],
      duration: duration,
      brightness: params[:brightness],
      light_group_id: params[:group_id]
    )
    
    TaskScheduler.scehdule_task(task) unless ENV['RAILS_ENV'] == 'test'
    redirect_to "/groups/#{params[:group_id]}"
  end

  def test
    task = Task.find(params[:id])
    result = TaskExecutor.execute(task)
    redirect_link = "/groups/#{task.light_group_id}/tasks/#{task.id}"
    flash[:test_result] = result
    redirect_to redirect_link
  end

  def destroy
    Task.find(params[:id]).destroy
    redirect_to "/groups/#{params[:group_id]}"
  end

  private 

  def binary_days(params)
    days = 0
    params.each do |key, value|
      days += value.to_i if key.to_s.include?('day')
    end

    return days
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper

end

app/views/groups/index.erb
<% @groups.each do |group| %>
  <div class='light-group'>
    <a href='/groups/<%= group.hue_id %>'><%= group.name %></a>
  </div>
<% end %>

app/views/groups/show.erb
<h1><%= @group.name %></h1>

<% if @group.tasks.length.zero? %>
  No Schedules set
<% else %>
  <ul>
    <% @group.tasks.each do |task| %>
    <li><a href="/groups/<%= @group.hue_id %>/tasks/<%= task.id %>"><%= task.name %></a></li>
    <% end %>
  </ul>
<% end %>

<br>
<a href='/groups/<%= @group.hue_id %>/tasks/new'>Schedule Task</a>
<br>
<% @group.lights.each do |light| %>
  <div class='light'>
    <%= light.name %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LightsAndSoundsAlarm</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">  </head>
    <link rel="stylesheet" type="text/css" href=<%= @css_path %>>  
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">Lights and Sounds</a>
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="/sidekiq">Sidekiq</a>
          </li>
        </ul>
      </nav>
    </header>
    <div class='container'>
      <%= yield %>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with model:@task, url: group_tasks_url do %>
  <div class="form-group">
    <label for="task_name">Name Your Task</label> 
    <input id="task_name" name="task_name" placeholder="Turn Shit On" type="text" class="form-control">
  </div>
  <div class="form-group">
    <div>
      <div class="custom-control custom-checkbox custom-control-inline">
        <input name="monday" id="checkbox_0" type="checkbox" class="custom-control-input" id='1' value="1"> 
        <label for="checkbox_0" class="custom-control-label">Monday</label>
      </div>
      <div class="custom-control custom-checkbox custom-control-inline">
        <input name="tuesday" id="checkbox_1" type="checkbox" class="custom-control-input" value="2"> 
        <label for="checkbox_1" class="custom-control-label">Tuesday</label>
      </div>
      <div class="custom-control custom-checkbox custom-control-inline">
        <input name="wednesday" id="checkbox_2" type="checkbox" class="custom-control-input" value="4"> 
        <label for="checkbox_2" class="custom-control-label">Wednesday</label>
      </div>
      <div class="custom-control custom-checkbox custom-control-inline">
        <input name="thursday" id="checkbox_3" type="checkbox" class="custom-control-input" value="8"> 
        <label for="checkbox_3" class="custom-control-label">Thursday</label>
      </div>
      <div class="custom-control custom-checkbox custom-control-inline">
        <input name="friday" id="checkbox_4" type="checkbox" class="custom-control-input" value="16"> 
        <label for="checkbox_4" class="custom-control-label">Friday</label>
      </div>
      <div class="custom-control custom-checkbox custom-control-inline">
        <input name="saturday" id="checkbox_5" type="checkbox" class="custom-control-input" value="32"> 
        <label for="checkbox_5" class="custom-control-label">Saturday</label>
      </div>
      <div class="custom-control custom-checkbox custom-control-inline">
        <input name="sunday" id="checkbox_6" type="checkbox" class="custom-control-input" value="64"> 
        <label for="checkbox_6" class="custom-control-label">Sunday</label>
      </div>
    </div>
  </div>
  <div class='form-group'>
    <label for='time'>Time: </label>
    <input type="time" name="time" id='time'>
  </div> 
  <div class="form-group">
    <label>Action</label> 
    <div>
      <div class="custom-control custom-radio custom-control-inline">
        <input name="group_action" id="action_0" type="radio" class="custom-control-input" value="turn_on"> 
        <label for="action_0" class="custom-control-label">Turn On</label>
      </div>
      <div class="custom-control custom-radio custom-control-inline">
        <input name="group_action" id="action_1" type="radio" class="custom-control-input" value="turn_off"> 
        <label for="action_1" class="custom-control-label">Turn Off</label>
      </div>
    </div>
  </div> 
  <label for="brightness">Brightness:</label> 
  <div class="form-group">
    <input id="brightness" name="brightness" placeholder="0 - 255" type="text" class="form-control">
  </div>   
  <label for="transition-duration">Transition Duration</label> 
  <div class='row'>
    <div class='col-s'>
      <div class="form-group">
        <input id="transition-duration" name="transition-duration" placeholder="Some time" type="text" class="form-control">
      </div> 
    </div>
    <div class='col'>
      <div>
        <select id="duration_units" name="duration-units" class="custom-select">
          <option value="seconds">Seconds</option>
          <option value="minutes">Minutes</option>
        </select>
      </div>
    </div>
  </div>
  <div class="form-group">
    <button name="submit" type="submit" class="btn btn-primary">Submit</button>
  </div>
  <% end %>

app/views/tasks/new.erb
<%= render partial: 'form' %>

app/views/tasks/show.erb
<% if flash[:test_result] %>
  <div class="notice"><%= flash[:test_result] %></div>
<% end %>
<h1><%= @task.name %></h1>
<a href=<%= test_group_task_path %>>Test</a>
<br>
<% if @result == :success %>
  Tested OK!
<% elsif @result %>
  Something went wrong...
<% end %>
<br>
<p>Light Group: <%= @task.light_group.name %></p>
<p>
  Action: <%= @task.pretty_action %>
  <br>
  <% if @task.duration %>
    Duration: <%= @task.pretty_duration %>
  <% end%>

  <% if @task.brightness %>
    Brightness: <%= @task.brightness %>
  <% end%>
</p>

<p>
  Scheduled:
  <br>
  <%= "#{@days}, start time: #{@task.time}" %>
  <br>
  Created: <%= @task.created_at %>
</p>

<%= form_with model:@task, url: group_task_url, method: :delete  do |f| %>
<%= f.submit 'Delete',class: 'btn btn-danger' %>
<% end %>